[package]
name = "planter-platform"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
planter-core = { path = "../planter-core" }
thiserror.workspace = true
tokio.workspace = true
